[TRY-24] Change profile entity picture
Devgather/TIARY pull request #149
Opened 2022-12-29 03:22 UTC by leverest96

## Description

Change profile entity picture

## Changes

- Change profile entity picture

2022-12-29 03:23 UTC, leverest96 commented on src/main/java/me/tiary/service/ProfileService.java
> +        return ProfilePictureUploadResponseDto.builder()
만약에 modelMapper를 사용하게 된다면 profile로 매핑시켜도 괜찮을 것 같습니다.
builder와 modelMapper 중 어느 것이 더 나을까요?

2022-12-29 09:33 UTC, Igoc requested changes

2022-12-29 09:33 UTC, Igoc commented on src/main/java/me/tiary/domain/Profile.java
> +    public void updateProfilePicture(final String pictureUrl) {
Profile이라는 정보가 클래스명에 이미 있으므로, 메서드명을 updatePicture로 지으면 어떨까요?

2022-12-29 09:33 UTC, Igoc commented on src/main/java/me/tiary/dto/profile/ProfilePictureUploadRequestDto.java
> +    private final MultipartFile multipartFile;
multipartFile이라는 이름은 범용적으로 사용될 수 있기 때문에, API를 사용하는 입장에서 혼동이 올 수 있을 것 같습니다.

2022-12-29 09:33 UTC, Igoc commented on src/main/java/me/tiary/service/ProfileService.java
> +        return ProfilePictureUploadResponseDto.builder()
어차피 프로필에서 값을 꺼내오는 거라면, 반환되는 이름을 picture로 변경하고 Model Mapper를 이용하는 것이 나을 것 같습니다.

2022-12-29 09:33 UTC, Igoc commented on src/main/resources/properties/aws.yml
> +    url: ${AWS_STORAGE_URL:aws-storage-url}
URL이 필요하므로 기본값으로 aws-storage-url을 사용하기보단, [https://example.com](https://example.com/)으로 설정해두면 좋을 것 같습니다.

2022-12-29 09:33 UTC, Igoc commented on src/main/java/me/tiary/service/ProfileService.java
> +    public ProfilePictureUploadResponseDto uploadPicture(final String profileUuid, final ProfilePictureUploadRequestDto requestDto) {
해당 비즈니스 로직에서 엔티티를 업데이트하기 때문에, Transactional 어노테이션을 적용해야 합니다.

2022-12-29 09:33 UTC, Igoc commented on src/main/java/me/tiary/service/ProfileService.java
> +        final String pictureUrl = awsS3Manager.uploadFiles(titleGenerator, List.of(multipartFile)).get(0);
로직상 반환되는 값을 URL로 표현하는 것보다 Path라고 표현하는 것이 정확할 것 같습니다.

2022-12-29 09:33 UTC, Igoc commented on src/main/java/me/tiary/service/ProfileService.java
> +                .orElseThrow(() -> new ProfileException(ProfileStatus.NOT_EXISTING_PROFILE));
해당 로직이 프로필 사진 업로드 로직 이후에 위치하게 되면, 프로필이 실제로 존재하지 않더라도 업로드는 무조건 수행됩니다.

2022-12-29 09:33 UTC, Igoc commented on src/main/java/me/tiary/service/ProfileService.java
> +        profile.updateProfilePicture(awsStorageProperties.getUrl() + pictureUrl);
AWS Storage Properties의 URL 마지막에 /가 없는 경우도 존재할 수 있는데, 그러한 경우 최종적인 URL이 이상해지므로 처리를 해주어야 합니다.

2022-12-29 09:33 UTC, Igoc commented on src/test/java/me/tiary/domain/profile/UpdateProfilePictureTest.java
> +        final String profilePicture = "test";
프로필 사진 업데이트에 사용되는 변수이므로, URL 형식으로 구성되면 좋을 것 같습니다.

2022-12-29 09:33 UTC, Igoc commented on src/test/java/me/tiary/domain/profile/UpdateProfilePictureTest.java
> +        final String profilePicture = "test";
변수명을 사용하려는 메서드의 파라미터명과 동일하게 설정하면, 사용되는 위치가 어디인지 명확해질 것 같습니다.

2022-12-29 09:33 UTC, Igoc commented on src/test/java/me/tiary/domain/profile/UpdateProfilePictureTest.java
> +        assertThat(profile.getPicture()).isNotNull();
null 여부를 검증하기보단, 업데이트에 사용된 프로필 사진 URL이 들어가 있는지 검증할 필요가 있습니다.

2022-12-29 09:33 UTC, Igoc commented on src/test/java/me/tiary/service/profileservice/UploadPictureTest.java
> +        final ProfilePictureUploadRequestDto requestDto = ProfilePictureUploadRequestDto.builder()
별도의 Factory로 분리하면 중복을 제거할 수 있습니다.

2022-12-29 09:33 UTC, Igoc commented on src/test/java/me/tiary/service/profileservice/UploadPictureTest.java
> +    void failIfProfileDoesNotExist() {
로직 순서를 수정해야 하기 때문에, 해당 테스트도 같이 수정되어야 합니다.

2022-12-29 09:33 UTC, Igoc commented on src/test/java/me/tiary/service/profileservice/UploadPictureTest.java
> +        final ProfilePictureUploadRequestDto requestDto = ProfilePictureUploadRequestDto.builder()
해당 변수와 관련된 것들을 Mocking 아래에 위치시키면, 테스트 코드를 위에서부터 순차적으로 읽으면서 파악하기가 쉬워집니다.

실제 로직의 흐름이 순차적으로 떠오르도록 테스트 코드를 구성해 주세요.

2022-12-29 09:33 UTC, Igoc commented on src/test/java/me/tiary/service/profileservice/UploadPictureTest.java
> +        assertThat(result.getPictureUrl()).isEqualTo(awsStorageProperties.getUrl() + fileNameList.get(0));
Profile Repository에서 반환되는 프로필에 담긴 URL 과의 괴리가 있습니다.

2022-12-29 12:57 UTC, leverest96 commented on src/main/java/me/tiary/service/ProfileService.java
> +        profile.updateProfilePicture(awsStorageProperties.getUrl() + pictureUrl);
환경변수(.../)로 이미 등록되어 있는 property를 데리고 옴에도 불구하고 마지막에 /가 존재하는 경우가 생길 수 있을까요?

2022-12-29 12:57 UTC, leverest96 commented on src/test/java/me/tiary/service/profileservice/UploadPictureTest.java
> +        assertThat(result.getPictureUrl()).isEqualTo(awsStorageProperties.getUrl() + fileNameList.get(0));
정확히 어떤 의미인지 잘 모르겠습니다.

2022-12-30 10:34 UTC, Igoc commented on src/test/java/me/tiary/service/profileservice/UploadPictureTest.java
> +        assertThat(result.getPictureUrl()).isEqualTo(awsStorageProperties.getUrl() + fileNameList.get(0));
expected 값으로 프로필의 picture가 오는 것이 맞을 것 같습니다.

2022-12-30 10:35 UTC, Igoc commented on src/main/java/me/tiary/service/ProfileService.java
> +        profile.updateProfilePicture(awsStorageProperties.getUrl() + pictureUrl);
URL의 마지막 부분에 /가 반드시 오도록 강제할 수 없기 때문에, 별도로 처리하는 로직이 필요합니다.

2022-12-30 12:11 UTC, Igoc approved these changes

2022-12-30 12:17 UTC, closed without merging