[TR-9] Create JWT generation method in JWT provider
Devgather/TIARY pull request #15
Opened 2022-11-18 16:09 UTC by yunicho

## Description

Create JWT generation method in JWT provider

## Changes

- Create JWT generation method in JWT provider

2022-11-18 16:11 UTC, yunicho commented
JWTProvider generate 메서드에 대한 테스트코드 생성의 실패테스트 경우가 명확치 않아 payload 논의 후 추가 작성하는 것으로 하겠습니다.

2022-11-20 19:31 UTC, Igoc reviewed
페이로드의 Value 타입으로 지원되지 않는 타입이 설정되어 IllegalArgumentException이 발생하는지와 [InvalidKeyException](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/security/InvalidKeyException.html)이 발생하는 시크릿 키를 사용하여 SignatureGenerationException이 발생하는지를 테스트하면 될 것 같습니다.

2022-11-22 14:46 UTC, yunicho commented
>

2022-11-24 02:06 UTC, yunicho commented
> 페이로드의 Value 타입으로 지원되지 않는 타입이 설정되어 IllegalArgumentException이 발생하는지와 [InvalidKeyException](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/security/InvalidKeyException.html)이 발생하는 시크릿 키를 사용하여 SignatureGenerationException이 발생하는지를 테스트하면 될 것 같습니다.

2022-11-24 06:15 UTC, Igoc requested changes

2022-11-24 06:15 UTC, Igoc commented on src/main/java/me/tiary/utility/jwt/JwtProvider.java
> +    public JwtProvider(final JwtProperties properties) throws JWTDecodeException {
생성자에서 JWTDecodeException 예외가 던져지는 경우가 있나요?

2022-11-24 06:15 UTC, Igoc commented on src/main/java/me/tiary/utility/jwt/JwtProvider.java
> +    public String generate(Map<String, ?> payload) throws JWTCreationException {
파라미터가 내부에서 변경되지 않으므로, final 키워드를 추가하면 좋을 것 같습니다.

2022-11-24 06:15 UTC, Igoc commented on src/test/java/me/tiary/utility/jwt/jwtprovider/GenerateTest.java
> +public class GenerateTest {
테스트 클래스는 외부에서 사용될 일이 없으므로, public으로 구성하지 않는 것이 좋을 것 같습니다.

2022-11-24 06:15 UTC, Igoc commented on src/test/java/me/tiary/utility/jwt/jwtprovider/GenerateTest.java
> +    void failIfPayloadTypeIsInvalid() {
개인적으로 실패 테스트가 먼저 정의되고, 성공 테스트가 뒤에 정의되면 코드를 파악하는 데 도움이 될 것 같습니다.

2022-11-24 06:33 UTC, Igoc approved these changes

2022-11-24 06:39 UTC, merged