[DG-11] Create profile creation API
Devgather/TIARY pull request #16
Opened 2022-10-10 12:30 UTC by leverest96

## Description

Create profile creation API

## Changes

- [x] Create profile creation API

2022-10-10 20:14 UTC, Igoc commented on src/test/java/me/tiary/controller/ProfileControllerTest.java
> +    void failToCreateProfileWithNullNickname() throws Exception {
기존에 Null Nickname 형식이 아니라, Nickname Null 형식으로 표현하셨었는데 수정이 가능할까요?

2022-10-10 20:21 UTC, Igoc commented on src/test/java/me/tiary/controller/ProfileControllerTest.java
> +        final ProfileCreationResponseDto response = gson.fromJson(resultActions
When 절에 배치하는 것이 더 적절해 보이는데, 어떻게 생각하시나요?

2022-10-10 20:24 UTC, Igoc commented on src/test/java/me/tiary/service/ProfileServiceTest.java
> +        ProfileCreationRequestDto requestDto = ProfileCreationRequestDto.builder()
final 키워드를 적용하면 좋을 것 같습니다.

2022-10-10 20:25 UTC, Igoc commented on src/test/java/me/tiary/service/ProfileServiceTest.java
> +        Profile savedProfile = Profile.builder()
final 키워드를 적용하면 좋을 것 같습니다.

2022-10-11 02:34 UTC, Igoc requested changes

2022-10-11 02:34 UTC, Igoc commented on src/main/java/me/tiary/controller/ProfileController.java
> +            @ApiResponse(responseCode = "404", description = "존재하지 않는 파라미터", content = @Content(schema = @Schema(implementation = GlobalExceptionHandler.ExceptionResponse.class))),
이미 존재하는 닉네임에 대한 응답을 표현한 것 같은데, 응답 코드와 설명이 잘못 작성되어 있는 것 같습니다.

2022-10-11 02:39 UTC, yunicho reviewed
minor detail 수정 코멘트 제안

2022-10-11 02:39 UTC, yunicho commented on src/main/java/me/tiary/status/ProfileStatus.java
> +    EXISTING_NICKNAME(HttpStatus.CONFLICT, "must be unique nickname");
must be "a" 오타 수정 부탁드립니다

2022-10-11 02:39 UTC, yunicho commented on src/test/java/me/tiary/controller/ProfileControllerTest.java
> +    @DisplayName("프로필 생성 실패 - blank nickname")
empty nickname 실패 테스트와 이름이 헷갈리는데 blank in nickname으로 수정 제안합니다

2022-10-11 02:56 UTC, Igoc approved these changes

2022-10-11 02:57 UTC, merged