[TR-19] Create profile creation api
Devgather/TIARY pull request #17
Opened 2022-11-21 02:44 UTC by leverest96

## Description

Create profile creation api

## Changes

- Create profile creation api

2022-11-21 10:30 UTC, Igoc requested changes

2022-11-21 10:30 UTC, Igoc commented on src/main/java/me/tiary/exception/handler/controller/GlobalExceptionHandler.java
> +    public ResponseEntity<Object> handleProfileException(ProfileException ex) {
파라미터가 내부에서 변경되지 않으므로, final 키워드를 추가하면 좋을 것 같습니다.

2022-11-21 10:30 UTC, Igoc commented on src/main/java/me/tiary/controller/ProfileController.java
> +    public ResponseEntity<ProfileCreationResponseDto> createProfile(@RequestBody @Valid final ProfileCreationRequestDto requestDto) {
닉네임 최대 허용 길이를 테스트하는 메서드가 없습니다.

2022-11-21 10:30 UTC, Igoc commented on src/test/java/me/tiary/controller/profilecontroller/CreateProfileTest.java
> +    @DisplayName("[Success] nickname is acceptable")
nickname is acceptable 대신 profile is acceptable이라고 표현하는 것이 더 적합할 것 같습니다.

2022-11-21 11:04 UTC, leverest96 commented on src/main/java/me/tiary/controller/ProfileController.java
> +    public ResponseEntity<ProfileCreationResponseDto> createProfile(@RequestBody @Valid final ProfileCreationRequestDto requestDto) {
dto에 적용된 validation을 다시 한번 검사 해야 할까요?
할 경우 테스트 코드를 추가하고, 안 할 경우 not blank에 대한 코드도 지워야 할 듯 합니다.

2022-11-21 11:19 UTC, Igoc commented on src/main/java/me/tiary/controller/ProfileController.java
> +    public ResponseEntity<ProfileCreationResponseDto> createProfile(@RequestBody @Valid final ProfileCreationRequestDto requestDto) {
어떤 Validation을 적용할 것인지는 개발자가 정하는 것이기 때문에, 개인적으로 테스트 코드 작성이 필요하다고 생각합니다.

2022-11-22 01:16 UTC, Igoc approved these changes

2022-11-22 01:19 UTC, merged