[DG-18] Create profile update API
Devgather/TIARY pull request #23
Opened 2022-10-14 16:46 UTC by leverest96

## Description

Create profile update API

## Changes

- [x] Create profile update API

2022-10-17 02:19 UTC, Igoc requested changes

2022-10-17 02:19 UTC, Igoc commented on src/test/java/me/tiary/controller/ProfileControllerTest.java
> +
변경된 내용이 없을 때 예외가 던져지는 것에 대한 테스트가 없습니다.

2022-10-17 02:19 UTC, Igoc commented on src/test/java/me/tiary/controller/ProfileControllerTest.java
> +                .updateProfile("Test", requestDto);
eq가 추가되면 좋을 것 같습니다.

2022-10-17 02:19 UTC, Igoc commented on src/test/java/me/tiary/controller/ProfileControllerTest.java
> +                .updateProfile("Test", requestDto);
eq가 추가되면 좋을 것 같습니다.

2022-10-17 02:19 UTC, Igoc commented on src/test/java/me/tiary/controller/ProfileControllerTest.java
> +                .updateProfile("Test", requestDto);
eq가 추가되면 좋을 것 같습니다.

2022-10-17 02:19 UTC, Igoc commented on src/test/java/me/tiary/service/ProfileServiceTest.java
> +                .findByNickname("Test");
eq가 추가되면 좋을 것 같습니다.

2022-10-17 02:19 UTC, Igoc commented on src/test/java/me/tiary/service/ProfileServiceTest.java
> +                .findByNickname("Test");
eq가 추가되면 좋을 것 같습니다.

2022-10-17 02:19 UTC, Igoc commented on src/test/java/me/tiary/service/ProfileServiceTest.java
> +                .findByNickname("Test");
eq가 추가되면 좋을 것 같습니다.

2022-10-17 02:19 UTC, Igoc commented on src/test/java/me/tiary/service/ProfileServiceTest.java
> +                .findByNickname("ExistingNickname");
eq가 추가되면 좋을 것 같습니다.

2022-10-17 02:19 UTC, Igoc commented on src/test/java/me/tiary/service/ProfileServiceTest.java
> +                .findByNickname("Test");
eq가 추가되면 좋을 것 같습니다.

2022-10-17 02:19 UTC, Igoc commented on src/test/java/me/tiary/service/ProfileServiceTest.java
> +
변경하려는 닉네임에 대한 Repository 조회 Mocking이 빠져 있습니다.

2022-10-17 02:19 UTC, Igoc commented on src/test/java/me/tiary/service/ProfileServiceTest.java
> +        doReturn(Optional.ofNullable(Profile.builder().build()))
조회 결과로 나온 프로필에 아무런 값도 설정되어 있지 않아서, 해당 테스트를 실패할 것 같은데 성공 처리가 되었나요?

2022-10-17 02:19 UTC, Igoc commented on src/test/java/me/tiary/service/ProfileServiceTest.java
> +        doReturn(Optional.ofNullable(Profile.builder().build()))
로직 순서상 조회 결과로 나온 프로필에 값이 설정되어 있어야 할 것 같은데, 아무런 값도 설정되어 있지 않습니다.

2022-10-17 02:19 UTC, Igoc commented on src/test/java/me/tiary/service/ProfileServiceTest.java
> +        doReturn(Optional.ofNullable(Profile.builder().build()))
로직 순서상 조회 결과로 나온 프로필에 값이 설정되어 있어야 할 것 같은데, 아무런 값도 설정되어 있지 않습니다.

2022-10-17 07:02 UTC, leverest96 commented on src/test/java/me/tiary/service/ProfileServiceTest.java
> +        doReturn(Optional.ofNullable(Profile.builder().build()))
기존 코드에서 확장성을 고려하지 않은 채로 pathVariable로 받아온 nickname만을 고려하여 비교하였기 때문에 성공처리가 됐었습니다.
확장성을 고려하여 코드 수정 후 추가했습니다.

2022-10-17 07:15 UTC, leverest96 commented on src/main/java/me/tiary/service/ProfileService.java
> +        if (requestDto.getNickname().equals(nickname)) {
변경되지 않은 항목으로 수정 완료를 클릭했을 때 수정 완료라는 문구가 뜬다면, 유저 입장에서 버그라고 오인할 수 있을 것 같습니다.
판별하게 될 경우, nickname 중복 확인에서도 코드를 추가해야 할 필요가 있어 보입니다.

2022-10-20 04:25 UTC, Igoc requested changes

2022-10-20 04:25 UTC, Igoc commented on src/main/java/me/tiary/service/ProfileService.java
> +        final boolean updateProfile = profile.updateProfile(requestDto);
updateProfile이라는 변수명은 업데이트된 프로필이 담겨있는 변수라는 착각을 줄 수 있을 것 같습니다.

참, 거짓을 담고 있음을 나타낼 수 있는 이름으로 변경하면 좋을 것 같습니다.

2022-10-20 04:25 UTC, Igoc commented on src/test/java/me/tiary/controller/ProfileControllerTest.java
> +        // Then
예외 메시지에 대한 검증이 같이 이루어지면 좋을 것 같습니다.

2022-10-20 04:25 UTC, Igoc commented on src/main/java/me/tiary/domain/Profile.java
> +            this.nickname = requestDto.getNickname();
변경하려는 닉네임의 양 끝에 공백이 포함된 경우, 추후 조회 등이 불가능한 문제가 발생할 수 있을 것 같습니다.

필드를 업데이트할 때 trim() 된 값으로 업데이트하면 좋을 것 같습니다.

2022-10-20 04:25 UTC, Igoc commented on src/test/java/me/tiary/domain/ProfileTest.java
> +@ExtendWith(MockitoExtension.class)
해당 테스트에서 Mockito 기능이 사용되지 않았음에도 불필요하게 어노테이션이 붙어있는 것 같습니다.

2022-10-20 04:25 UTC, Igoc commented on src/test/java/me/tiary/domain/ProfileTest.java
> +    @DisplayName("프로필 수정 성공 - not changed nickname")
제 생각엔 해당 테스트 코드에서 false를 반환하기 때문에, 실패 테스트라고 보이는데 어떻게 생각하시나요?

2022-10-20 04:25 UTC, Igoc commented on src/test/java/me/tiary/service/ProfileServiceTest.java
> +    @DisplayName("프로필 수정 실패 - not changed nickname")
다루려는 예외에 부합하려면 not changed profile이라고 표현하는 것이 좋을 것 같습니다.

2022-10-20 04:35 UTC, yunicho commented on src/test/java/me/tiary/domain/ProfileTest.java
> +    @DisplayName("프로필 수정 성공 - not changed nickname")
프로필 안에 닉네임 말고 이미지만 변경할 수도 있으므로 미리 수정 성공으로 테스트 만들어둔 거로 보이는데 맞을까요?

2022-10-20 04:35 UTC, yunicho commented on src/test/java/me/tiary/service/ProfileServiceTest.java
> +    @DisplayName("프로필 수정 실패 - not existing profile")
해당 단위테스트에서 애초에 profile이 존재하지 않는데 프로필 update request가 들어올 수가 있는지 궁금합니다

2022-10-20 05:58 UTC, leverest96 commented on src/main/java/me/tiary/domain/Profile.java
> +        }
기존에는 else if 문으로 계속 추가하려고 했으나 service와의 통일성을 위해 if 문으로 구성하는 것도 괜찮을 것 같습니다.

2022-10-20 06:13 UTC, leverest96 commented on src/test/java/me/tiary/domain/ProfileTest.java
> +    @DisplayName("프로필 수정 성공 - not changed nickname")
두 번 꼬아서 생각했던 것 같습니다. updateProfile이라는 함수를 결국 통과하면서 false라는 값을 리턴하기 때문에 성공이라고 적었는데 의미 자체가 실패가 맞는 것 같습니다.

2022-10-20 06:14 UTC, yunicho commented on src/test/java/me/tiary/controller/ProfileControllerTest.java
> +    @DisplayName("프로필 수정 실패 - not existing profile about PathVariable")
about PathVariable은 어떤 detail을 명시하기 위해서 사용된 건가요?

2022-10-20 06:17 UTC, leverest96 commented on src/test/java/me/tiary/controller/ProfileControllerTest.java
> +    @DisplayName("프로필 수정 실패 - not existing profile about PathVariable")
pathVariable으로 들어온 것과 requestBody로 들어온 것을 분리시켜 테스트를 하기 위해 적어놨습니다!
url에 있는 것이 pathVariable이고 requestDto가 requestBody입니다 :)

2022-10-20 06:19 UTC, leverest96 commented on src/test/java/me/tiary/service/ProfileServiceTest.java
> +    @DisplayName("프로필 수정 실패 - not existing profile")
service에서 로직을 보면 프로필이 존재하는지 우선 체크하기 때문에 만든 테스트입니다!

2022-10-20 06:21 UTC, leverest96 commented on src/main/java/me/tiary/domain/Profile.java
> +            this.nickname = requestDto.getNickname();
controller에서 이미 trim된 상태로 보내줌에도 불구하고 또 trim을 하는 것이 맞을까요?

2022-10-20 09:06 UTC, Igoc commented on src/main/java/me/tiary/domain/Profile.java
> +        }
저는 if 문안에 &&으로 여러 조건이 연달아서 묶이는 경우를 생각했었는데, if ~ else if ~ else 구조를 사용할 수도 있겠네요.

생각지도 못하고 있었던 방법인데, 스타일에 따라서는 그렇게 구성해도 좋을 것 같습니다.

2022-10-20 09:10 UTC, Igoc commented on src/main/java/me/tiary/domain/Profile.java
> +            this.nickname = requestDto.getNickname();
Path Variable로 넘어오는 닉네임에 대해서는 trim()이 적용되지만, Request Body에 대해서는 trim()이 따로 적용되지 않고 있는 것 같습니다.

그러면 저장할 때 양 끝에 공백이 포함된 닉네임이 저장될 수 있게 되고, 향후 해당 닉네임을 조회하려면 trim()이 일어나서 조회를 못하게 됩니다.

2022-10-20 09:49 UTC, leverest96 commented on src/main/java/me/tiary/domain/Profile.java
> +            this.nickname = requestDto.getNickname();
관련된 케이스 수정 완료했습니다. 해당 케이스에 대해서는 마지막 commit을 봐주세요!

2022-10-20 09:54 UTC, Igoc approved these changes

2022-10-20 10:00 UTC, merged