[TR-12] FEAT: Create login business logic
Devgather/TIARY pull request #62
Opened 2022-12-08 06:35 UTC by yunicho

## Description

Create login business logic

## Changes

- Create login business logic

2022-12-08 08:26 UTC, Igoc requested changes

2022-12-08 08:26 UTC, Igoc commented on src/main/java/me/tiary/dto/account/AccountLoginRequestDto.java
> +@AllArgsConstructor
final 키워드가 붙은 필드로만 구성되어 있기 때문에, AllArgsConstructor 대신 RequiredArgsConstructor를 사용하면 좋을 것 같습니다.

2022-12-08 08:26 UTC, Igoc commented on src/main/java/me/tiary/dto/account/AccountLoginRequestDto.java
> +public class AccountLoginRequestDto {
Request DTO의 경우 Controller에서 RequestBody를 통해 값을 주입받을 텐데, 이때 Reflection을 이용해서 값이 주입되기 때문에 기본 생성자가 반드시 있어야 합니다.

2022-12-08 08:26 UTC, Igoc commented on src/main/java/me/tiary/dto/account/AccountLoginResultDto.java
> +@AllArgsConstructor
final 키워드가 붙은 필드로만 구성되어 있기 때문에, AllArgsConstructor 대신 RequiredArgsConstructor를 사용하면 좋을 것 같습니다.

2022-12-08 08:26 UTC, Igoc commented on src/main/java/me/tiary/exception/status/AccountStatus.java
> +    NOT_MATCHING_PASSWORD(HttpStatus.FORBIDDEN, "must provide matching email and password");
비밀번호를 틀린 경우 인증을 실패한 것이기 때문에, Forbidden 대신 Unauthorized 상태 코드를 반환하는 것이 더 적절할 것 같습니다.

2022-12-08 08:26 UTC, Igoc commented on src/main/java/me/tiary/service/AccountService.java
> +        Optional<Account> account = accountRepository.findByEmail(requestDto.getEmail());
변경되지 않는 변수이므로, final 키워드를 추가하면 좋을 것 같습니다.

2022-12-08 08:26 UTC, Igoc commented on src/main/java/me/tiary/service/AccountService.java
> +        if (account.isEmpty()) {
Optional의 orElseThrow 메서드를 이용하면 더 좋을 것 같습니다.

2022-12-08 08:26 UTC, Igoc commented on src/main/java/me/tiary/service/AccountService.java
> +        final String uuid = account.get().getProfile().getUuid();
findByEmail 메서드는 Account 엔티티만 영속화하기 때문에, 지연 로딩으로 Profile을 불러오는 순간 N + 1 문제가 발생할 것 같습니다.

2022-12-08 08:26 UTC, Igoc commented on src/main/java/me/tiary/service/AccountService.java
> +        final Map<String, String> payload = new HashMap<>();
Access Token과 Refresh Token의 페이로드가 항상 동일하다는 보장이 없기 때문에, 각각에 대한 페이로드를 따로 만들어주는 것이 좋을 것 같습니다.

2022-12-08 08:26 UTC, Igoc commented on src/main/java/me/tiary/service/AccountService.java
> +        return modelMapper.map(result, AccountLoginResultDto.class);
Model Mapper가 불필요하게 사용된 것 같습니다.

2022-12-08 08:26 UTC, Igoc commented on src/test/java/me/tiary/service/accountservice/LoginTest.java
> +    @DisplayName("[Success] Credentials are acceptable")
Convention에 따라 테스트를 설명하는 문장은 소문자로만 구성해 주세요.

2022-12-08 08:26 UTC, Igoc commented on src/test/java/me/tiary/service/accountservice/LoginTest.java
> +    void SuccessIfCredentialsAreAcceptable() {
자바의 메서드명 Convention에 따라, Pascal 표기법이 아니라 Camel 표기법으로 나타내주세요.

2022-12-08 08:26 UTC, Igoc commented on src/test/java/me/tiary/service/accountservice/LoginTest.java
> +        doReturn(Optional.of(account))
null일 경우를 허용하기 위해 of 대신 ofNullable로 감싸주세요.

2022-12-08 08:26 UTC, Igoc commented on src/test/java/me/tiary/service/accountservice/LoginTest.java
> +                .findByEmail(eq(requestDto.getEmail()));
동작 구조상 account의 이메일과 동일할 경우 수행하도록 하는 것이 맞을 것 같습니다.

2022-12-12 10:32 UTC, Igoc requested changes

2022-12-12 10:32 UTC, Igoc commented on src/main/java/me/tiary/service/AccountService.java
> +    @Transactional
Transactional 처리를 하지 않아도 될 것 같습니다.

2022-12-12 10:32 UTC, Igoc commented on src/main/java/me/tiary/service/AccountService.java
> +        final Map<String, String> payload = new HashMap<>();
변수명을 payload 대신 accessTokenPayload 등으로 지으면 좋을 것 같습니다.

2022-12-12 15:23 UTC, yunicho commented on src/main/java/me/tiary/service/AccountService.java
> +        final String uuid = account.get().getProfile().getUuid();
해당 부분 N+1 문제는 새로운 이슈를 열어 대응하는 것으로 하겠습니다.

2022-12-13 02:55 UTC, Igoc approved these changes

2022-12-13 02:58 UTC, merged