[TR-43] Create profile picture upload business logic
Devgather/TIARY pull request #97
Opened 2022-12-15 08:52 UTC by leverest96

## Description

Create profile picture upload business logic

## Changes

- Create profile picture upload business logic

2022-12-15 08:54 UTC, leverest96 commented
max size에 대한 테스트는 추후 size를 설정할 수 있는 방법을 알게 되었을 때 진행하겠습니다. 또한 테스트에서 MockMultipartFile의 bytes[]를 임의로originalFileName.getBytes()로 설정해두었는데 다른 방법이 필요하다면 코멘트 부탁드립니다.

2022-12-16 02:32 UTC, yunicho commented on src/main/java/me/tiary/exception/status/ProfileStatus.java
> +    NOT_EXISTING_CONTENT_TYPE(HttpStatus.NOT_FOUND, "must be an existing content type"),
NOT_EXISTING_CONTENT_TYPE을 하기 status와 의미가 헷갈릴 수 있을 것 같습니다. NOT_CONTAINING_CONTENT 등으로 변경하는 것이 어떨까요?

2022-12-16 02:32 UTC, yunicho commented on src/main/java/me/tiary/exception/status/ProfileStatus.java
> +    IMPROPER_CONTENT_TYPE(HttpStatus.BAD_REQUEST, "must be an proper content type");
Improper content type보다 우리가 지원하지 않는다는 의미를 살려 NOT_SUPPORTING 으로 하면 의미전달에도, 통일성에도 도움이 될 것 같습니다.

2022-12-16 02:40 UTC, Igoc requested changes
final 키워드를 적용할 수 있는 곳인데, 빠져있는 부분들이 있어 추가되면 좋을 것 같습니다.

파일 크기 체크의 경우 서블릿 옵션으로 설정해두었으므로 컨트롤러단에서 검사하면 될 것 같습니다.

파일 크기 체크에 대해서는 [MultipartProperties의 max-file-size, max-request-size](https://velog.io/@park2348190/MultipartProperties%EC%9D%98-max-file-size-max-request-size%EC%9D%98-%EC%B0%A8%EC%9D%B4)를 참고하시면 될 것 같습니다.

2022-12-16 02:40 UTC, Igoc commented on src/main/java/me/tiary/exception/status/ProfileStatus.java
> +    NOT_EXISTING_CONTENT_TYPE(HttpStatus.NOT_FOUND, "must be an existing content type"),
서버의 자원을 찾지 못한 것이 아니므로, Bad Request 상태 코드를 반환하는 것이 맞을 것 같습니다.

2022-12-16 02:40 UTC, Igoc commented on src/main/java/me/tiary/service/ProfileService.java
> +    public List<String> uploadPicture(final String uuid, final MultipartFile multipartFile) {
UUID가 많은 곳에서 사용되기 때문에, 해당 UUID가 어떤 UUID를 가리키는지 헷갈립니다.

2022-12-16 02:40 UTC, Igoc commented on src/main/java/me/tiary/service/ProfileService.java
> +        if (contentType.matches("jpeg|png|gif|bmp")) {
if 문에서 실패 예외를 반환하면 else를 쓰지 않아도 되어서 코드 흐름이 깔끔해질 것 같습니다.

2022-12-16 02:40 UTC, Igoc commented on src/main/java/me/tiary/service/ProfileService.java
> +        if (contentType.matches("jpeg|png|gif|bmp")) {
MIME 타입에는 정해진 규칙이 있습니다.

자세한 정보는 [Common MIME types](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types)를 참고하시면 될 것 같습니다.

2022-12-16 02:40 UTC, Igoc commented on src/main/java/me/tiary/utility/aws/FileExtensionGenerator.java
> +package me.tiary.utility.aws;
해당 유틸리티의 경우 AWS에 종속적인 것이 아니므로, common의 하위로 포함되면 좋을 것 같습니다.

2022-12-16 02:40 UTC, Igoc commented on src/main/java/me/tiary/utility/aws/FileExtensionGenerator.java
> +            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "must be a proper format");
해당 객체가 HTTP와 엮어서 동작할 필요는 없을 것 같습니다.

2022-12-16 02:40 UTC, Igoc commented on src/test/java/me/tiary/service/profileservice/UploadPictureTest.java
> +@ExtendWith(MockitoExtension.class)
서비스 테스트를 나타내기 위한 어노테이션을 만들어두었으므로 이용하면 좋을 것 같습니다.

2022-12-16 02:40 UTC, Igoc commented on src/test/java/me/tiary/service/profileservice/UploadPictureTest.java
> +    static MockMultipartFile getMockMultipartFile(String originalFilename, String contentType, byte[] bytes) {
별도의 팩토리 객체로 분리하면 좋을 것 같습니다.

2022-12-16 02:40 UTC, Igoc commented on src/test/java/me/tiary/service/profileservice/UploadPictureTest.java
> +    static MockMultipartFile getMockMultipartFile(String originalFilename, String contentType, byte[] bytes) {
바이트 데이터의 경우 MIME 타입에 맞는 적절한 값을 포함해야 하지만, 목업 객체이므로 난수 값으로 생성해도 될 것 같습니다.

바이트 난수 값을 생성하는 방법은 [Random](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Random.html)을 참고하시면 될 것 같습니다.

2022-12-20 11:00 UTC, Igoc requested changes

2022-12-20 11:00 UTC, Igoc commented on src/main/java/me/tiary/exception/status/ProfileStatus.java
> +    NOT_CONTAINING_CONTENT(HttpStatus.NOT_FOUND, "must be an existing content type"),
Content Type이 없어도 Content는 존재할 수 있으므로, NOT_EXISTING_CONTENT_TYPE 등의 이름으로 변경되면 좋을 것 같습니다.

2022-12-20 11:00 UTC, Igoc commented on src/main/java/me/tiary/exception/status/ProfileStatus.java
> +    NOT_SUPPORTING(HttpStatus.BAD_REQUEST, "must be an proper content type");
NOT_SUPPORTING은 너무 범용적인 문장인 것 같습니다.

2022-12-20 11:00 UTC, Igoc commented on src/main/java/me/tiary/exception/status/ProfileStatus.java
> +    NOT_CONTAINING_CONTENT(HttpStatus.NOT_FOUND, "must be an existing content type"),
서버의 자원을 찾지 못한 것이 아니므로, Bad Request 상태 코드를 반환하는 것이 맞을 것 같습니다.

2022-12-20 11:00 UTC, Igoc commented on src/main/java/me/tiary/service/ProfileService.java
> +        return (originalFileName) -> profileUuid + "/profile/picture" + FileUtility.getFileExtension(originalFileName);
/profile/picture 값을 매직 넘버로 사용하는 대신, PROFILE_PICUTRE_PATH 등의 상수로 만들어두면 좋을 것 같습니다.

2022-12-20 11:00 UTC, Igoc commented on src/main/java/me/tiary/utility/common/FileUtility.java
> +            throw new IllegalArgumentException();
확장자가 없을 경우 예외를 던지는 것보다, 빈 문자열을 반환하도록 로직을 구성하는 것이 더 좋을 것 같은데 어떻게 생각하시나요?

2022-12-20 11:00 UTC, Igoc commented on src/test/java/me/tiary/service/profileservice/UploadPictureTest.java
> +        // Then
반환된 리스트의 길이도 같이 검증되면 좋을 것 같습니다.

2022-12-21 05:47 UTC, Igoc approved these changes

2022-12-21 05:53 UTC, merged